---
version: 2
archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
builds:
  - binary: watermeter-image-processor
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    ldflags:
      - -X 'main.Version={{ .Tag }}'
      - -X 'main.Gitsha={{ .ShortCommit }}'
    main: ./cmd/processor
source:
  enabled: true
signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - "--bundle=${signature}"
      - "${artifact}"
    artifacts: all
    output: true
sboms:
  - artifacts: archive
  - id: source
    artifacts: source
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/muhlba91/watermeter-image-processor:latest-amd64
      - ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_SHA }}-amd64
      - ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_TAG }}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --build-arg=CI_COMMIT_TIMESTAMP="{{ .Env.CI_COMMIT_TIMESTAMP }}"
      - --build-arg=CI_COMMIT_SHA="{{ .Env.CI_COMMIT_SHA }}"
      - --build-arg=CI_COMMIT_TAG="{{ .Env.CI_COMMIT_TAG }}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/muhlba91/watermeter-image-processor:latest-arm64
      - ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_SHA }}-arm64
      - ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_TAG }}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --build-arg=CI_COMMIT_TIMESTAMP="{{ .Env.CI_COMMIT_TIMESTAMP }}"
      - --build-arg=CI_COMMIT_SHA="{{ .Env.CI_COMMIT_SHA }}"
      - --build-arg=CI_COMMIT_TAG="{{ .Env.CI_COMMIT_TAG }}"
docker_manifests:
  - name_template: ghcr.io/muhlba91/watermeter-image-processor:latest
    image_templates:
      - ghcr.io/muhlba91/watermeter-image-processor:latest-amd64
      - ghcr.io/muhlba91/watermeter-image-processor:latest-arm64
  - name_template: ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_SHA }}
    image_templates:
      - ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_SHA }}-amd64
      - ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_SHA }}-arm64
  - name_template: ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_TAG }}
    image_templates:
      - ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_TAG }}-amd64
      - ghcr.io/muhlba91/watermeter-image-processor:{{ .Env.CI_COMMIT_TAG }}-arm64
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT"
