---
name: Verify ESPHome

on:
  push:
    branches:
      - main
    paths:
      - esphome/**
      - testing/esphome.yaml
      - .ci/**
      - .github/workflows/verify-esphome.yml
  pull_request:
    paths:
      - esphome/**
      - testing/esphome.yaml
      - .ci/**
      - .github/workflows/verify-esphome.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  esphome:
    runs-on: ubuntu-latest
    name: Verify ESPHome Firmware
    timeout-minutes: 30

    steps:
      - uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - run: |
          cp .ci/secrets.yaml testing/secrets.yaml

      - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: esphome
          tags: esphome:latest
          push: false

      - uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: esphome:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            esphome compile testing/esphome.yaml
